package modelo.dominio.dto;

// Generated 11-jun-2015 19:38:57 by Hibernate Tools 4.3.1

/**
 * EmpDetailsView generated by hbm2java
 */
public class EmpDetailsView extends ObjectDTO implements java.io.Serializable {

	private EmpDetailsViewId id;

	public EmpDetailsView() {
	}

	public EmpDetailsView(EmpDetailsViewId id) {
		this.id = id;
	}

	public EmpDetailsViewId getId() {
		return this.id;
	}

	public void setId(EmpDetailsViewId id) {
		this.id = id;
	}

}
