package modelo.dominio.dto;

// Generated 11-jun-2015 19:38:57 by Hibernate Tools 4.3.1

/**
 * JobHistory generated by hbm2java
 */
public class JobHistory extends ObjectDTO  implements java.io.Serializable {

	private JobHistoryId id;
	private Departments departments;
	private Jobs jobs;
	private Employees employees;

	public JobHistory() {
	}

	public JobHistory(JobHistoryId id, Jobs jobs, Employees employees) {
		this.id = id;
		this.jobs = jobs;
		this.employees = employees;
	}

	public JobHistory(JobHistoryId id, Departments departments, Jobs jobs,
			Employees employees) {
		this.id = id;
		this.departments = departments;
		this.jobs = jobs;
		this.employees = employees;
	}

	public JobHistoryId getId() {
		return this.id;
	}

	public void setId(JobHistoryId id) {
		this.id = id;
	}

	public Departments getDepartments() {
		return this.departments;
	}

	public void setDepartments(Departments departments) {
		this.departments = departments;
	}

	public Jobs getJobs() {
		return this.jobs;
	}

	public void setJobs(Jobs jobs) {
		this.jobs = jobs;
	}

	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

}
